import type { ThemeDefinition } from "@/features/theme/types";
import { buildThemePalette } from "@/features/theme/tokens/deriveSemanticTokens";

const deepForestCore = {
  primary: "#9eb8a8",
  primaryContainer: "#2f4f41",
  primaryFixed: "#c8e2d4",
  primaryFixedDim: "#a8c7b6",
  onPrimary: "#0b1f17",
  onPrimaryContainer: "#d2e8db",
  onPrimaryFixed: "#0b1f17",
  onPrimaryFixedVariant: "#284636",
  secondary: "#c9b08a",
  secondaryContainer: "#5a4a32",
  secondaryOnContainer: "#f2e2c8",
  secondaryFixed: "#e8d7bc",
  secondaryFixedDim: "#d4bf9f",
  onSecondary: "#261a0a",
  onSecondaryContainer: "#f2e2c8",
  onSecondaryFixed: "#261a0a",
  onSecondaryFixedVariant: "#4f3f28",
  tertiary: "#4a5f42",
  tertiaryContainer: "#55694c",
  tertiaryFixed: "#d8e5cb",
  tertiaryFixedDim: "#becbae",
  onTertiary: "#f4f7f0",
  onTertiaryContainer: "#dce6d2",
  onTertiaryFixed: "#141e0c",
  onTertiaryFixedVariant: "#3a4a32",
  background: "#0f1a14",
  onBackground: "#e3ebe6",
  surface: "#152820",
  surfaceDim: "#0c1611",
  surfaceBright: "#1a3128",
  surfaceVariant: "#2a4036",
  surfaceContainer: "#1e342a",
  surfaceContainerLow: "#1a2f26",
  surfaceContainerLowest: "#152820",
  surfaceContainerHigh: "#243d32",
  surfaceContainerHighest: "#2d4a3d",
  surfaceTint: "#9eb8a8",
  onSurface: "#e6ede8",
  onSurfaceVariant: "#b3c8bb",
  inverseSurface: "#e6ede8",
  inverseOnSurface: "#152820",
  inversePrimary: "#2f4f41",
  outline: "#5f7a6b",
  outlineVariant: "#3d5649",
  error: "#ffb4ab",
  errorContainer: "#7f2d28",
  onError: "#1d0907",
  onErrorContainer: "#ffdad6",
  backdrop: "rgba(8, 16, 12, 0.72)",
  transparent: "transparent",
} as const;

const deepForestColors = buildThemePalette(deepForestCore, { isDark: true }, {
  statusThriving: deepForestCore.tertiaryContainer,
  onStatusThriving: deepForestCore.onTertiaryContainer,
  statusStable: deepForestCore.surfaceContainerHigh,
  onStatusStable: deepForestCore.onSurfaceVariant,
  memorialAccent: deepForestCore.secondaryFixedDim,
  journalAccent: deepForestCore.primaryFixedDim,
});

export const deepForestTheme: ThemeDefinition = {
  id: "deep-forest",
  name: "Deep Forest",
  description: "The quiet serenity of a midnight woods.",
  category: "dark",
  isDark: true,
  quote: "In every walk with nature one receives far more than he seeks.",
  colors: deepForestColors,
  preview: {
    plantTitle: "Monstera",
    statusLabel: "Thriving",
    image: require("@/assets/images/silver-satin-pothos-trailing-from-a-shelf.png"),
    imageOpacity: 0.88,
    surfaces: {
      background: deepForestCore.surfaceContainer,
      border: "rgba(182, 200, 187, 0.12)",
      plantTitle: deepForestCore.primaryFixedDim,
      statusBackground: deepForestCore.tertiaryContainer,
      statusForeground: deepForestCore.onTertiaryContainer,
      placeholderPrimary: deepForestCore.surfaceContainerHigh,
      placeholderSecondary: deepForestCore.surfaceContainerHighest,
    },
  },
  card: {
    background: deepForestCore.primaryContainer,
    title: deepForestCore.onPrimaryContainer,
    description: deepForestCore.onSurfaceVariant,
    editorialLabel: deepForestCore.secondaryFixedDim,
    editorialQuote: deepForestCore.primaryFixedDim,
    selectionRing: deepForestCore.primaryFixed,
    selectionFill: deepForestCore.primary,
    selectionIcon: deepForestCore.onPrimary,
    unselectedRing: "rgba(168, 199, 182, 0.35)",
    editorialDivider: deepForestCore.surfaceContainerHigh,
  },
  accessibility: {
    passesWcagAa: true,
    bodyContrastRatio: 0,
    secondaryContrastRatio: 0,
    statusChipContrastRatio: 0,
    notes: [],
  },
};
