import type { ThemeDefinition } from "@/features/theme/types";
import { buildThemePalette } from "@/features/theme/tokens/deriveSemanticTokens";

const deepForestCore = {
  primary: "#a3bdb0",
  primaryContainer: "#2a4a3c",
  primaryFixed: "#c8e2d4",
  primaryFixedDim: "#8fb39f",
  onPrimary: "#0b1f17",
  onPrimaryContainer: "#d4ebe0",
  onPrimaryFixed: "#0b1f17",
  onPrimaryFixedVariant: "#284636",
  secondary: "#c4a67a",
  secondaryContainer: "#4f3f2a",
  secondaryOnContainer: "#f0e4cc",
  secondaryFixed: "#e4d4b8",
  secondaryFixedDim: "#c9b08a",
  onSecondary: "#1f1608",
  onSecondaryContainer: "#f0e4cc",
  onSecondaryFixed: "#261a0a",
  onSecondaryFixedVariant: "#4f3f28",
  tertiary: "#4d6344",
  tertiaryContainer: "#55694c",
  tertiaryFixed: "#d0dfc4",
  tertiaryFixedDim: "#b3c7a8",
  onTertiary: "#f2f6ee",
  onTertiaryContainer: "#dce6d2",
  onTertiaryFixed: "#141e0c",
  onTertiaryFixedVariant: "#3a4a32",
  background: "#0e1813",
  onBackground: "#e8f0eb",
  surface: "#142720",
  surfaceDim: "#0a1410",
  surfaceBright: "#1b3128",
  surfaceVariant: "#253d34",
  surfaceContainer: "#1a2f26",
  surfaceContainerLow: "#172922",
  surfaceContainerLowest: "#121f1a",
  surfaceContainerHigh: "#243b32",
  surfaceContainerHighest: "#2d483e",
  surfaceTint: "#a3bdb0",
  onSurface: "#e8f0eb",
  onSurfaceVariant: "#b8cdc2",
  inverseSurface: "#e8f0eb",
  inverseOnSurface: "#142720",
  inversePrimary: "#2a4a3c",
  outline: "#5f7a6b",
  outlineVariant: "#3f574c",
  error: "#ffb4ab",
  errorContainer: "#6f2a25",
  onError: "#1d0907",
  onErrorContainer: "#ffdad6",
  backdrop: "rgba(8, 16, 12, 0.72)",
  transparent: "transparent",
  selectionCardBackground: "#2a4a3c",
} as const;

const deepForestColors = buildThemePalette(deepForestCore, { isDark: true }, {
  statusThriving: deepForestCore.primaryFixed,
  onStatusThriving: deepForestCore.onPrimaryFixed,
  statusStable: deepForestCore.surfaceContainerHigh,
  onStatusStable: deepForestCore.onSurfaceVariant,
  memorialAccent: deepForestCore.secondaryFixedDim,
  journalAccent: deepForestCore.primaryFixedDim,
  shadow: "rgba(0, 0, 0, 0.32)",
  dangerGradientEnd: "#5c1f1a",
});

export const deepForestTheme: ThemeDefinition = {
  id: "deep-forest",
  name: "Deep Forest",
  description: "The quiet serenity of a midnight woods.",
  access: "premium",
  category: "dark",
  isDark: true,
  quote: "In every walk with nature one receives far more than he seeks.",
  colors: deepForestColors,
  preview: {
    plantTitle: "Monstera",
    statusLabel: "Thriving",
    image: require("@/assets/images/silver-satin-pothos-trailing-from-a-shelf.png"),
    imageOpacity: 0.88,
    surfaces: {
      background: deepForestCore.surfaceContainer,
      border: deepForestColors.suggestionCardBorder,
      plantTitle: deepForestCore.primaryFixedDim,
      statusBackground: deepForestCore.primaryFixed,
      statusForeground: deepForestCore.onPrimaryFixed,
      placeholderPrimary: deepForestCore.surfaceContainerHigh,
      placeholderSecondary: deepForestCore.surfaceContainerHighest,
    },
  },
  card: {
    background: deepForestCore.selectionCardBackground,
    title: deepForestCore.onPrimaryContainer,
    description: deepForestCore.onSurfaceVariant,
    editorialLabel: deepForestCore.secondaryFixedDim,
    editorialQuote: deepForestCore.primaryFixedDim,
    selectionRing: deepForestCore.primaryFixed,
    selectionFill: deepForestCore.primary,
    selectionIcon: deepForestCore.onPrimary,
    unselectedRing: deepForestColors.borderSubtle,
    editorialDivider: deepForestCore.surfaceContainerHigh,
  },
  accessibility: {
    passesWcagAa: true,
    bodyContrastRatio: 0,
    secondaryContrastRatio: 0,
    statusChipContrastRatio: 0,
    notes: [],
  },
};
