import type { ThemeDefinition } from "@/features/theme/types";

const deepForestColors = {
  primary: "#a9cfb9",
  primaryContainer: "#2d4f3e",
  primaryFixed: "#c5ebd4",
  primaryFixedDim: "#a9cfb9",
  onPrimary: "#002113",
  onPrimaryContainer: "#9ac0aa",
  onPrimaryFixed: "#002113",
  onPrimaryFixedVariant: "#2c4e3d",
  secondary: "#ffb59c",
  secondaryContainer: "#fd9e7c",
  secondaryOnContainer: "#77331a",
  secondaryFixed: "#ffdbcf",
  secondaryFixedDim: "#ffb59c",
  onSecondary: "#390c00",
  onSecondaryContainer: "#77331a",
  onSecondaryFixed: "#390c00",
  onSecondaryFixedVariant: "#763219",
  tertiary: "#404c36",
  tertiaryContainer: "#404c36",
  tertiaryFixed: "#dae7c9",
  tertiaryFixedDim: "#becbae",
  onTertiary: "#ffffff",
  onTertiaryContainer: "#becbae",
  onTertiaryFixed: "#141e0c",
  onTertiaryFixedVariant: "#3f4a35",
  background: "#122820",
  onBackground: "#e8f0eb",
  surface: "#163828",
  surfaceDim: "#0f2219",
  surfaceBright: "#1a3d2c",
  surfaceVariant: "#254234",
  surfaceContainer: "#1f3a2f",
  surfaceContainerLow: "#1a3429",
  surfaceContainerLowest: "#163828",
  surfaceContainerHigh: "#254234",
  surfaceContainerHighest: "#2d4f3e",
  surfaceTint: "#a9cfb9",
  onSurface: "#e8f0eb",
  onSurfaceVariant: "#9ac0aa",
  inverseSurface: "#e8f0eb",
  inverseOnSurface: "#163828",
  inversePrimary: "#163828",
  outline: "#5a7a68",
  outlineVariant: "#3a5c4a",
  error: "#ffb4ab",
  errorContainer: "#93000a",
  onError: "#690005",
  onErrorContainer: "#ffdad6",
  backdrop: "rgba(8, 16, 12, 0.72)",
  transparent: "transparent",
} as const;

export const deepForestTheme: ThemeDefinition = {
  id: "deep-forest",
  name: "Deep Forest",
  description: "The quiet serenity of a midnight woods.",
  category: "dark",
  isDark: true,
  quote: "In every walk with nature one receives far more than he seeks.",
  colors: deepForestColors,
  preview: {
    plantTitle: "Monstera",
    statusLabel: "Thriving",
    image: require("@/assets/images/silver-satin-pothos-trailing-from-a-shelf.png"),
    imageOpacity: 0.8,
    surfaces: {
      background: "#163828",
      border: "rgba(255, 255, 255, 0.05)",
      plantTitle: deepForestColors.primaryFixed,
      statusBackground: "#404c36",
      statusForeground: "#becbae",
      placeholderPrimary: "rgba(45, 79, 62, 0.4)",
      placeholderSecondary: "rgba(45, 79, 62, 0.4)",
    },
  },
  card: {
    background: deepForestColors.primaryContainer,
    title: deepForestColors.onPrimaryContainer,
    description: "rgba(169, 207, 185, 0.7)",
    editorialLabel: deepForestColors.secondaryFixedDim,
    editorialQuote: "rgba(169, 207, 185, 0.6)",
    selectionRing: deepForestColors.primaryFixed,
    selectionFill: deepForestColors.primaryFixed,
    selectionIcon: deepForestColors.onPrimary,
    unselectedRing: "rgba(169, 207, 185, 0.3)",
    editorialDivider: "rgba(45, 79, 62, 0.4)",
  },
  accessibility: {
    passesWcagAa: true,
    bodyContrastRatio: 9.2,
    secondaryContrastRatio: 5.1,
    statusChipContrastRatio: 4.8,
    notes: [],
  },
};
