import type { ThemeDefinition } from "@/features/theme/types";
import { buildThemePalette } from "@/features/theme/tokens/deriveSemanticTokens";

const linenLightCore = {
  primary: "#163828",
  primaryContainer: "#2d4f3e",
  primaryFixed: "#c5ebd4",
  primaryFixedDim: "#a9cfb9",
  onPrimary: "#ffffff",
  onPrimaryContainer: "#9ac0aa",
  onPrimaryFixed: "#002113",
  onPrimaryFixedVariant: "#2c4e3d",
  secondary: "#94492e",
  secondaryContainer: "#fd9e7c",
  secondaryOnContainer: "#77331a",
  secondaryFixed: "#ffdbcf",
  secondaryFixedDim: "#ffb59c",
  onSecondary: "#ffffff",
  onSecondaryContainer: "#77331a",
  onSecondaryFixed: "#390c00",
  onSecondaryFixedVariant: "#763219",
  tertiary: "#2a3521",
  tertiaryContainer: "#404c36",
  tertiaryFixed: "#dae7c9",
  tertiaryFixedDim: "#becbae",
  onTertiary: "#ffffff",
  onTertiaryContainer: "#afbca0",
  onTertiaryFixed: "#141e0c",
  onTertiaryFixedVariant: "#3f4a35",
  background: "#fbf9f4",
  onBackground: "#1b1c19",
  surface: "#fbf9f4",
  surfaceDim: "#dbdad5",
  surfaceBright: "#fbf9f4",
  surfaceVariant: "#e4e2dd",
  surfaceContainer: "#f0eee9",
  surfaceContainerLow: "#f5f3ee",
  surfaceContainerLowest: "#ffffff",
  surfaceContainerHigh: "#eae8e3",
  surfaceContainerHighest: "#e4e2dd",
  surfaceTint: "#436653",
  onSurface: "#1b1c19",
  onSurfaceVariant: "#414844",
  inverseSurface: "#30312e",
  inverseOnSurface: "#f2f1ec",
  inversePrimary: "#a9cfb9",
  outline: "#727973",
  outlineVariant: "#c1c8c2",
  error: "#ba1a1a",
  errorContainer: "#ffdad6",
  onError: "#ffffff",
  onErrorContainer: "#93000a",
  backdrop: "rgba(27, 28, 25, 0.32)",
  transparent: "transparent",
} as const;

const linenLightColors = buildThemePalette(linenLightCore, { isDark: false }, {
  /** Pre-expansion destructive CTA gradient end (PrimaryButton). */
  dangerGradientEnd: "#8c1414",
});

export const linenLightTheme: ThemeDefinition = {
  id: "linen-light",
  name: "Linen Light",
  description: "Inspired by sun-drenched conservatories.",
  category: "light",
  isDark: false,
  quote: "Nature does not hurry, yet everything is accomplished.",
  colors: linenLightColors,
  preview: {
    plantTitle: "Monstera",
    statusLabel: "Thriving",
    image: require("@/assets/images/lush-green-monstera-deliciosa.png"),
    surfaces: {
      background: linenLightCore.surface,
      border: "rgba(193, 200, 194, 0.1)",
      plantTitle: linenLightCore.primary,
      statusBackground: linenLightCore.tertiaryContainer,
      statusForeground: linenLightCore.onTertiaryContainer,
      placeholderPrimary: linenLightCore.surfaceContainer,
      placeholderSecondary: linenLightCore.surfaceContainer,
    },
  },
  card: {
    background: linenLightCore.surfaceContainerLowest,
    title: linenLightCore.primary,
    description: linenLightCore.onSurfaceVariant,
    editorialLabel: linenLightCore.secondary,
    editorialQuote: linenLightCore.onSurfaceVariant,
    selectionRing: linenLightCore.primary,
    selectionFill: linenLightCore.primary,
    selectionIcon: linenLightCore.onPrimary,
    unselectedRing: "rgba(22, 56, 40, 0.3)",
    editorialDivider: linenLightCore.surfaceContainer,
  },
  accessibility: {
    passesWcagAa: true,
    bodyContrastRatio: 0,
    secondaryContrastRatio: 0,
    statusChipContrastRatio: 0,
    notes: [],
  },
};
