import type { ThemeDefinition } from "@/features/theme/types";
import { buildThemePalette } from "@/features/theme/tokens/deriveSemanticTokens";

const midnightIvyCore = {
  primary: "#6b9f82",
  primaryContainer: "#1f3f30",
  primaryFixed: "#a9cfb9",
  primaryFixedDim: "#8bb69d",
  onPrimary: "#ffffff",
  onPrimaryContainer: "#c5e0d0",
  onPrimaryFixed: "#0b1f17",
  onPrimaryFixedVariant: "#284636",
  secondary: "#b8c9b8",
  secondaryContainer: "#2a3f34",
  secondaryOnContainer: "#dce8dc",
  secondaryFixed: "#c5ebd4",
  secondaryFixedDim: "#a3bca8",
  onSecondary: "#0f1a14",
  onSecondaryContainer: "#dce8dc",
  onSecondaryFixed: "#0b1f17",
  onSecondaryFixedVariant: "#2c4e3d",
  tertiary: "#243128",
  tertiaryContainer: "#2f4036",
  tertiaryFixed: "#d0e2c8",
  tertiaryFixedDim: "#b3c7ad",
  onTertiary: "#eef2eb",
  onTertiaryContainer: "#c8d6c0",
  onTertiaryFixed: "#141e0c",
  onTertiaryFixedVariant: "#3a4a32",
  background: "#060908",
  onBackground: "#eceee9",
  surface: "#0c100e",
  surfaceDim: "#040605",
  surfaceBright: "#121816",
  surfaceVariant: "#2a332e",
  surfaceContainer: "#121816",
  surfaceContainerLow: "#0f1311",
  surfaceContainerLowest: "#0c100e",
  surfaceContainerHigh: "#1a211d",
  surfaceContainerHighest: "#232b27",
  surfaceTint: "#8bb69d",
  onSurface: "#eceee9",
  onSurfaceVariant: "#adb6af",
  inverseSurface: "#eceee9",
  inverseOnSurface: "#121816",
  inversePrimary: "#6b9f82",
  outline: "#56615a",
  outlineVariant: "#3a4440",
  error: "#ffb4ab",
  errorContainer: "#7f2d28",
  onError: "#2b0b09",
  onErrorContainer: "#ffdad6",
  backdrop: "rgba(0, 0, 0, 0.76)",
  transparent: "transparent",
} as const;

const midnightIvyColors = buildThemePalette(midnightIvyCore, { isDark: true }, {
  statusThriving: midnightIvyCore.primaryContainer,
  onStatusThriving: midnightIvyCore.onPrimaryContainer,
  statusStable: midnightIvyCore.surfaceContainerHigh,
  onStatusStable: midnightIvyCore.onSurfaceVariant,
  shadow: "rgba(0, 0, 0, 0.36)",
  timelineAccent: midnightIvyCore.primary,
});

export const midnightIvyTheme: ThemeDefinition = {
  id: "midnight-ivy",
  name: "Midnight Ivy",
  description: "A deep, nocturnal sanctuary for high-contrast focus.",
  category: "dark",
  isDark: true,
  quote: "In the heart of the night, the garden breathes its deepest secrets.",
  colors: midnightIvyColors,
  preview: {
    plantTitle: "Ivy Wall",
    statusLabel: "Thriving",
    image: require("@/assets/images/dark-ivy-leaves-in-high-contrast.png"),
    imageOpacity: 0.9,
    surfaces: {
      background: midnightIvyCore.surfaceContainerHigh,
      border: "rgba(173, 182, 175, 0.14)",
      plantTitle: midnightIvyCore.primaryFixedDim,
      statusBackground: midnightIvyCore.primary,
      statusForeground: midnightIvyCore.onPrimary,
      placeholderPrimary: midnightIvyCore.surfaceContainerHighest,
      placeholderSecondary: midnightIvyCore.outlineVariant,
    },
  },
  card: {
    background: midnightIvyCore.surfaceContainerHighest,
    title: midnightIvyCore.onSurface,
    description: midnightIvyCore.onSurfaceVariant,
    editorialLabel: midnightIvyCore.primaryFixedDim,
    editorialQuote: midnightIvyCore.onSurfaceVariant,
    selectionRing: midnightIvyCore.primary,
    selectionFill: midnightIvyCore.primary,
    selectionIcon: midnightIvyCore.onPrimary,
    unselectedRing: "rgba(173, 182, 175, 0.32)",
    editorialDivider: midnightIvyCore.outlineVariant,
  },
  accessibility: {
    passesWcagAa: true,
    bodyContrastRatio: 0,
    secondaryContrastRatio: 0,
    statusChipContrastRatio: 0,
    notes: [],
  },
};
