import type { ThemeDefinition } from "@/features/theme/types";

const midnightIvyColors = {
  primary: "#436653",
  primaryContainer: "#2c4e3d",
  primaryFixed: "#a9cfb9",
  primaryFixedDim: "#a9cfb9",
  onPrimary: "#ffffff",
  onPrimaryContainer: "#9ac0aa",
  onPrimaryFixed: "#002113",
  onPrimaryFixedVariant: "#2c4e3d",
  secondary: "#c5ebd4",
  secondaryContainer: "#2d4f3e",
  secondaryOnContainer: "#9ac0aa",
  secondaryFixed: "#c5ebd4",
  secondaryFixedDim: "#a9cfb9",
  onSecondary: "#002113",
  onSecondaryContainer: "#9ac0aa",
  onSecondaryFixed: "#002113",
  onSecondaryFixedVariant: "#2c4e3d",
  tertiary: "#1b3022",
  tertiaryContainer: "#254234",
  tertiaryFixed: "#dae7c9",
  tertiaryFixedDim: "#becbae",
  onTertiary: "#ffffff",
  onTertiaryContainer: "#afbca0",
  onTertiaryFixed: "#141e0c",
  onTertiaryFixedVariant: "#3f4a35",
  background: "#000000",
  onBackground: "#f2f1ec",
  surface: "#0a0a0a",
  surfaceDim: "#000000",
  surfaceBright: "#141414",
  surfaceVariant: "#e4e2dd",
  surfaceContainer: "#1a1a1a",
  surfaceContainerLow: "#121212",
  surfaceContainerLowest: "#0a0a0a",
  surfaceContainerHigh: "#242424",
  surfaceContainerHighest: "#30312e",
  surfaceTint: "#a9cfb9",
  onSurface: "#f2f1ec",
  onSurfaceVariant: "#c1c8c2",
  inverseSurface: "#30312e",
  inverseOnSurface: "#f2f1ec",
  inversePrimary: "#a9cfb9",
  outline: "#5c635e",
  outlineVariant: "#414844",
  error: "#ffb4ab",
  errorContainer: "#93000a",
  onError: "#ffffff",
  onErrorContainer: "#ffdad6",
  backdrop: "rgba(0, 0, 0, 0.8)",
  transparent: "transparent",
} as const;

export const midnightIvyTheme: ThemeDefinition = {
  id: "midnight-ivy",
  name: "Midnight Ivy",
  description: "A deep, nocturnal sanctuary for high-contrast focus.",
  category: "dark",
  isDark: true,
  quote: "In the heart of the night, the garden breathes its deepest secrets.",
  colors: midnightIvyColors,
  preview: {
    plantTitle: "Ivy Wall",
    statusLabel: "Thriving",
    image: require("@/assets/images/dark-ivy-leaves-in-high-contrast.png"),
    imageOpacity: 0.92,
    surfaces: {
      background: "rgba(0, 0, 0, 0.4)",
      border: "rgba(255, 255, 255, 0.08)",
      plantTitle: midnightIvyColors.surfaceVariant,
      statusBackground: midnightIvyColors.primary,
      statusForeground: midnightIvyColors.onPrimary,
      placeholderPrimary: "rgba(255, 255, 255, 0.1)",
      placeholderSecondary: "rgba(255, 255, 255, 0.1)",
    },
  },
  card: {
    background: midnightIvyColors.inverseSurface,
    title: midnightIvyColors.inverseOnSurface,
    description: "rgba(228, 226, 221, 0.6)",
    editorialLabel: midnightIvyColors.primaryFixedDim,
    editorialQuote: "rgba(228, 226, 221, 0.5)",
    selectionRing: midnightIvyColors.primaryFixed,
    selectionFill: midnightIvyColors.primary,
    selectionIcon: midnightIvyColors.onPrimary,
    unselectedRing: "rgba(228, 226, 221, 0.3)",
    editorialDivider: "rgba(255, 255, 255, 0.05)",
  },
  accessibility: {
    passesWcagAa: true,
    bodyContrastRatio: 14.8,
    secondaryContrastRatio: 6.2,
    statusChipContrastRatio: 5.4,
    notes: [],
  },
};
