import type { ThemeDefinition } from "@/features/theme/types";
import { buildThemePalette } from "@/features/theme/tokens/deriveSemanticTokens";

const midnightIvyCore = {
  primary: "#72a886",
  primaryContainer: "#1c3a2c",
  primaryFixed: "#a9cfb9",
  primaryFixedDim: "#8bb69d",
  onPrimary: "#ffffff",
  onPrimaryContainer: "#c8e4d4",
  onPrimaryFixed: "#0b1f17",
  onPrimaryFixedVariant: "#284636",
  secondary: "#a8b8a8",
  secondaryContainer: "#28362e",
  secondaryOnContainer: "#dce8dc",
  secondaryFixed: "#c0d8c8",
  secondaryFixedDim: "#9eb0a0",
  onSecondary: "#0f1a14",
  onSecondaryContainer: "#dce8dc",
  onSecondaryFixed: "#0b1f17",
  onSecondaryFixedVariant: "#2c4e3d",
  tertiary: "#243128",
  tertiaryContainer: "#2f4036",
  tertiaryFixed: "#d0e2c8",
  tertiaryFixedDim: "#b3c7ad",
  onTertiary: "#eef2eb",
  onTertiaryContainer: "#c8d6c0",
  onTertiaryFixed: "#141e0c",
  onTertiaryFixedVariant: "#3a4a32",
  background: "#070a09",
  onBackground: "#eef1ec",
  surface: "#0e1210",
  surfaceDim: "#050706",
  surfaceBright: "#141a17",
  surfaceVariant: "#252e2a",
  surfaceContainer: "#111614",
  surfaceContainerLow: "#0f1311",
  surfaceContainerLowest: "#0c100e",
  surfaceContainerHigh: "#1a221e",
  surfaceContainerHighest: "#242c28",
  surfaceTint: "#8bb69d",
  onSurface: "#eef1ec",
  onSurfaceVariant: "#b5bfb8",
  inverseSurface: "#eef1ec",
  inverseOnSurface: "#111614",
  inversePrimary: "#72a886",
  outline: "#56615a",
  outlineVariant: "#3a4440",
  error: "#ffb4ab",
  errorContainer: "#6f2a25",
  onError: "#2b0b09",
  onErrorContainer: "#ffdad6",
  backdrop: "rgba(0, 0, 0, 0.76)",
  transparent: "transparent",
} as const;

const midnightIvyColors = buildThemePalette(midnightIvyCore, { isDark: true }, {
  statusThriving: midnightIvyCore.primaryFixed,
  onStatusThriving: midnightIvyCore.onPrimaryFixed,
  statusStable: midnightIvyCore.surfaceContainerHigh,
  onStatusStable: midnightIvyCore.onSurfaceVariant,
  timelineAccent: midnightIvyCore.primary,
  shadow: "rgba(0, 0, 0, 0.36)",
  dangerGradientEnd: "#5c1f1a",
});

export const midnightIvyTheme: ThemeDefinition = {
  id: "midnight-ivy",
  name: "Midnight Ivy",
  description: "A deep, nocturnal sanctuary for high-contrast focus.",
  access: "premium",
  category: "dark",
  isDark: true,
  quote: "In the heart of the night, the garden breathes its deepest secrets.",
  colors: midnightIvyColors,
  preview: {
    plantTitle: "Ivy Wall",
    statusLabel: "Thriving",
    image: require("@/assets/images/dark-ivy-leaves-in-high-contrast.png"),
    imageOpacity: 0.9,
    surfaces: {
      background: midnightIvyCore.surfaceContainerHigh,
      border: midnightIvyColors.suggestionCardBorder,
      plantTitle: midnightIvyCore.primaryFixedDim,
      statusBackground: midnightIvyCore.primaryFixed,
      statusForeground: midnightIvyCore.onPrimaryFixed,
      placeholderPrimary: midnightIvyCore.surfaceContainerHighest,
      placeholderSecondary: midnightIvyCore.outlineVariant,
    },
  },
  card: {
    background: midnightIvyCore.surfaceContainerHighest,
    title: midnightIvyCore.onSurface,
    description: midnightIvyCore.onSurfaceVariant,
    editorialLabel: midnightIvyCore.primaryFixedDim,
    editorialQuote: midnightIvyCore.onSurfaceVariant,
    selectionRing: midnightIvyCore.primary,
    selectionFill: midnightIvyCore.primary,
    selectionIcon: midnightIvyCore.onPrimary,
    unselectedRing: midnightIvyColors.borderSubtle,
    editorialDivider: midnightIvyCore.outlineVariant,
  },
  accessibility: {
    passesWcagAa: true,
    bodyContrastRatio: 0,
    secondaryContrastRatio: 0,
    statusChipContrastRatio: 0,
    notes: [],
  },
};
