import type { ThemeDefinition } from "@/features/theme/types";

const terracottaColors = {
  primary: "#163828",
  primaryContainer: "#2d4f3e",
  primaryFixed: "#c5ebd4",
  primaryFixedDim: "#a9cfb9",
  onPrimary: "#ffffff",
  onPrimaryContainer: "#9ac0aa",
  onPrimaryFixed: "#002113",
  onPrimaryFixedVariant: "#2c4e3d",
  secondary: "#94492e",
  secondaryContainer: "#fd9e7c",
  secondaryOnContainer: "#77331a",
  secondaryFixed: "#ffdbcf",
  secondaryFixedDim: "#ffb59c",
  onSecondary: "#ffffff",
  onSecondaryContainer: "#77331a",
  onSecondaryFixed: "#390c00",
  onSecondaryFixedVariant: "#763219",
  tertiary: "#5c3d2c",
  tertiaryContainer: "#7a5238",
  tertiaryFixed: "#f2d4c4",
  tertiaryFixedDim: "#e4b9a3",
  onTertiary: "#ffffff",
  onTertiaryContainer: "#f8ebe4",
  onTertiaryFixed: "#2d1608",
  onTertiaryFixedVariant: "#5c3d2c",
  background: "#f8ebe4",
  onBackground: "#390c00",
  surface: "#f8ebe4",
  surfaceDim: "#ecd4c8",
  surfaceBright: "#fff5ef",
  surfaceVariant: "#f2d4c4",
  surfaceContainer: "#f5e3d8",
  surfaceContainerLow: "rgba(245, 243, 238, 0.6)",
  surfaceContainerLowest: "#fff8f4",
  surfaceContainerHigh: "#ecd4c8",
  surfaceContainerHighest: "#e4b9a3",
  surfaceTint: "#94492e",
  onSurface: "#390c00",
  onSurfaceVariant: "#763219",
  inverseSurface: "#390c00",
  inverseOnSurface: "#ffdbcf",
  inversePrimary: "#ffb59c",
  outline: "#b07a5d",
  outlineVariant: "#d9a48a",
  error: "#ba1a1a",
  errorContainer: "#ffdad6",
  onError: "#ffffff",
  onErrorContainer: "#93000a",
  backdrop: "rgba(57, 12, 0, 0.28)",
  transparent: "transparent",
} as const;

export const terracottaDuskTheme: ThemeDefinition = {
  id: "terracotta-dusk",
  name: "Terracotta Dusk",
  description: "The warmth of a Mediterranean garden at twilight.",
  category: "warm",
  isDark: false,
  quote: "Earth and clay remember the sun long after it has set.",
  colors: terracottaColors,
  preview: {
    plantTitle: "Cactus",
    statusLabel: "Thriving",
    image: require("@/assets/images/pilea-peperomioides.png"),
    surfaces: {
      background: terracottaColors.surfaceContainerLow,
      border: "rgba(118, 50, 25, 0.08)",
      plantTitle: terracottaColors.secondary,
      statusBackground: terracottaColors.secondaryContainer,
      statusForeground: terracottaColors.onSecondaryContainer,
      placeholderPrimary: "rgba(57, 12, 0, 0.05)",
      placeholderSecondary: "rgba(57, 12, 0, 0.05)",
    },
  },
  card: {
    background: terracottaColors.secondaryFixed,
    title: terracottaColors.onSecondaryFixed,
    description: terracottaColors.onSecondaryFixedVariant,
    editorialLabel: terracottaColors.secondary,
    editorialQuote: terracottaColors.onSecondaryFixedVariant,
    selectionRing: terracottaColors.secondary,
    selectionFill: terracottaColors.secondary,
    selectionIcon: terracottaColors.onSecondary,
    unselectedRing: "rgba(118, 50, 25, 0.3)",
    editorialDivider: "rgba(118, 50, 25, 0.1)",
  },
  accessibility: {
    passesWcagAa: true,
    bodyContrastRatio: 8.6,
    secondaryContrastRatio: 5.3,
    statusChipContrastRatio: 4.7,
    notes: [],
  },
};
