import type { ThemeDefinition } from "@/features/theme/types";
import { buildThemePalette } from "@/features/theme/tokens/deriveSemanticTokens";
import { withAlpha } from "@/features/theme/utils/withAlpha";

import { linenLightCore } from "./linenLight";

/** Picker card + preview tokens from Terracotta Dusk mockup (Linen secondary-fixed shell). */
const terracottaPickerCore = {
  selectionCardBackground: linenLightCore.secondaryFixed,
  cardTitle: linenLightCore.onSecondaryFixed,
  cardDescription: linenLightCore.onSecondaryFixedVariant,
  cardEditorialLabel: linenLightCore.secondary,
  cardEditorialQuote: linenLightCore.onSecondaryFixedVariant,
  cardDivider: withAlpha(linenLightCore.onSecondaryFixedVariant, 0.1),
  cardUnselectedRing: withAlpha(linenLightCore.onSecondaryFixedVariant, 0.3),
  selectionRing: linenLightCore.onSecondaryFixed,
  selectionFill: linenLightCore.secondary,
  selectionIcon: linenLightCore.onSecondary,
  previewBackground: withAlpha(linenLightCore.surfaceContainerLow, 0.6),
  previewPlantTitle: linenLightCore.secondary,
  previewStatusBackground: linenLightCore.secondaryContainer,
  previewStatusForeground: linenLightCore.onSecondaryContainer,
  previewPlaceholder: withAlpha(linenLightCore.onSecondaryFixed, 0.05),
} as const;

/** In-app Mediterranean palette when Terracotta Dusk is the active theme. */
const terracottaCore = {
  primary: "#2f4a3a",
  primaryContainer: "#4a6454",
  primaryFixed: "#c5e2d0",
  primaryFixedDim: "#a8c7b4",
  onPrimary: "#ffffff",
  onPrimaryContainer: "#e0f0e6",
  onPrimaryFixed: "#0f2219",
  onPrimaryFixedVariant: "#2f4a3a",
  secondary: "#8f5638",
  secondaryContainer: "#dcc4ae",
  secondaryOnContainer: "#5c321f",
  secondaryFixed: "#f0e0d4",
  secondaryFixedDim: "#e0cdb8",
  onSecondary: "#ffffff",
  onSecondaryContainer: "#5c321f",
  onSecondaryFixed: "#3d2218",
  onSecondaryFixedVariant: "#6b4638",
  tertiary: "#6f5444",
  tertiaryContainer: "#8a6c58",
  tertiaryFixed: "#f2e0d4",
  tertiaryFixedDim: "#e4c9b8",
  onTertiary: "#fffaf6",
  onTertiaryContainer: "#f8ebe4",
  onTertiaryFixed: "#3d2218",
  onTertiaryFixedVariant: "#6b4638",
  background: "#f4ebe3",
  onBackground: "#3d2218",
  surface: "#f6ebe3",
  surfaceDim: "#ead8cc",
  surfaceBright: "#fff8f4",
  surfaceVariant: "#f0ddd2",
  surfaceContainer: "#f3e4d9",
  surfaceContainerLow: "#efe0d4",
  surfaceContainerLowest: "#fffaf6",
  surfaceContainerHigh: "#e8d4c6",
  surfaceContainerHighest: "#d8c4b6",
  surfaceTint: "#8f5638",
  onSurface: "#3d2218",
  onSurfaceVariant: "#5c4030",
  inverseSurface: "#3d2218",
  inverseOnSurface: "#f4ddd0",
  inversePrimary: "#e0cdb8",
  outline: "#9a7260",
  outlineVariant: "#d4b29e",
  error: "#ba1a1a",
  errorContainer: "#ffdad6",
  onError: "#ffffff",
  onErrorContainer: "#93000a",
  backdrop: "rgba(61, 34, 24, 0.24)",
  transparent: "transparent",
  selectionCardBackground: terracottaPickerCore.selectionCardBackground,
} as const;

const terracottaColors = buildThemePalette(terracottaCore, { isDark: false }, {
  statusThriving: terracottaCore.primaryFixed,
  onStatusThriving: terracottaCore.onPrimaryFixed,
  statusStable: terracottaCore.surfaceContainerHigh,
  onStatusStable: terracottaCore.onSurfaceVariant,
  memorialAccent: terracottaCore.secondary,
  journalAccent: terracottaCore.primary,
  dangerGradientEnd: "#7a1515",
});

const terracottaPickerBorder = withAlpha(
  linenLightCore.onSecondaryFixedVariant,
  0.1,
);

export const terracottaDuskTheme: ThemeDefinition = {
  id: "terracotta-dusk",
  name: "Terracotta Dusk",
  description: "The warmth of a Mediterranean garden at twilight.",
  access: "premium",
  category: "warm",
  isDark: false,
  quote: "Earth and clay remember the sun long after it has set.",
  colors: terracottaColors,
  preview: {
    plantTitle: "Cactus",
    statusLabel: "Thriving",
    image: require("@/assets/images/pilea-peperomioides.png"),
    imageOpacity: 1,
    surfaces: {
      background: terracottaPickerCore.previewBackground,
      border: terracottaPickerBorder,
      plantTitle: terracottaPickerCore.previewPlantTitle,
      statusBackground: terracottaPickerCore.previewStatusBackground,
      statusForeground: terracottaPickerCore.previewStatusForeground,
      placeholderPrimary: terracottaPickerCore.previewPlaceholder,
      placeholderSecondary: terracottaPickerCore.previewPlaceholder,
    },
  },
  card: {
    background: terracottaPickerCore.selectionCardBackground,
    title: terracottaPickerCore.cardTitle,
    description: terracottaPickerCore.cardDescription,
    editorialLabel: terracottaPickerCore.cardEditorialLabel,
    editorialQuote: terracottaPickerCore.cardEditorialQuote,
    selectionRing: terracottaPickerCore.selectionRing,
    selectionFill: terracottaPickerCore.selectionFill,
    selectionIcon: terracottaPickerCore.selectionIcon,
    unselectedRing: terracottaPickerCore.cardUnselectedRing,
    editorialDivider: terracottaPickerCore.cardDivider,
  },
  accessibility: {
    passesWcagAa: true,
    bodyContrastRatio: 0,
    secondaryContrastRatio: 0,
    statusChipContrastRatio: 0,
    notes: [],
  },
};
