import type { ThemeDefinition } from "@/features/theme/types";
import { buildThemePalette } from "@/features/theme/tokens/deriveSemanticTokens";

const terracottaCore = {
  primary: "#2f4a3a",
  primaryContainer: "#4a6454",
  primaryFixed: "#c5e2d0",
  primaryFixedDim: "#a8c7b4",
  onPrimary: "#ffffff",
  onPrimaryContainer: "#e0f0e6",
  onPrimaryFixed: "#0f2219",
  onPrimaryFixedVariant: "#2f4a3a",
  secondary: "#8f5638",
  secondaryContainer: "#dcc4ae",
  secondaryOnContainer: "#5c321f",
  secondaryFixed: "#f0e0d4",
  secondaryFixedDim: "#e0cdb8",
  onSecondary: "#ffffff",
  onSecondaryContainer: "#5c321f",
  onSecondaryFixed: "#3d2218",
  onSecondaryFixedVariant: "#6b4638",
  tertiary: "#6f5444",
  tertiaryContainer: "#8a6c58",
  tertiaryFixed: "#f2e0d4",
  tertiaryFixedDim: "#e4c9b8",
  onTertiary: "#fffaf6",
  onTertiaryContainer: "#f8ebe4",
  onTertiaryFixed: "#3d2218",
  onTertiaryFixedVariant: "#6b4638",
  background: "#f4ebe3",
  onBackground: "#3d2218",
  surface: "#f6ebe3",
  surfaceDim: "#ead8cc",
  surfaceBright: "#fff8f4",
  surfaceVariant: "#f0ddd2",
  surfaceContainer: "#f3e4d9",
  surfaceContainerLow: "#efe0d4",
  surfaceContainerLowest: "#fffaf6",
  surfaceContainerHigh: "#e8d4c6",
  surfaceContainerHighest: "#d8c4b6",
  surfaceTint: "#8f5638",
  onSurface: "#3d2218",
  onSurfaceVariant: "#5c4030",
  inverseSurface: "#3d2218",
  inverseOnSurface: "#f4ddd0",
  inversePrimary: "#e0cdb8",
  outline: "#9a7260",
  outlineVariant: "#d4b29e",
  error: "#ba1a1a",
  errorContainer: "#ffdad6",
  onError: "#ffffff",
  onErrorContainer: "#93000a",
  backdrop: "rgba(61, 34, 24, 0.24)",
  transparent: "transparent",
} as const;

const terracottaColors = buildThemePalette(terracottaCore, { isDark: false }, {
  statusThriving: terracottaCore.primaryFixed,
  onStatusThriving: terracottaCore.onPrimaryFixed,
  statusStable: terracottaCore.surfaceContainerHigh,
  onStatusStable: terracottaCore.onSurfaceVariant,
  memorialAccent: terracottaCore.secondary,
  journalAccent: terracottaCore.primary,
  dangerGradientEnd: "#7a1515",
});

export const terracottaDuskTheme: ThemeDefinition = {
  id: "terracotta-dusk",
  name: "Terracotta Dusk",
  description: "The warmth of a Mediterranean garden at twilight.",
  access: "premium",
  category: "warm",
  isDark: false,
  quote: "Earth and clay remember the sun long after it has set.",
  colors: terracottaColors,
  preview: {
    plantTitle: "Cactus",
    statusLabel: "Thriving",
    image: require("@/assets/images/pilea-peperomioides.png"),
    surfaces: {
      background: terracottaCore.surfaceContainerLow,
      border: terracottaColors.suggestionCardBorder,
      plantTitle: terracottaCore.primary,
      statusBackground: terracottaCore.primaryFixed,
      statusForeground: terracottaCore.onPrimaryFixed,
      placeholderPrimary: terracottaCore.surfaceContainer,
      placeholderSecondary: terracottaCore.surfaceVariant,
    },
  },
  card: {
    background: terracottaCore.surfaceContainerLowest,
    title: terracottaCore.primary,
    description: terracottaCore.onSurfaceVariant,
    editorialLabel: terracottaCore.secondary,
    editorialQuote: terracottaCore.onSurfaceVariant,
    selectionRing: terracottaCore.primary,
    selectionFill: terracottaCore.primary,
    selectionIcon: terracottaCore.onPrimary,
    unselectedRing: terracottaColors.borderSubtle,
    editorialDivider: terracottaCore.surfaceContainerHigh,
  },
  accessibility: {
    passesWcagAa: true,
    bodyContrastRatio: 0,
    secondaryContrastRatio: 0,
    statusChipContrastRatio: 0,
    notes: [],
  },
};
