import type { User } from "@supabase/supabase-js";

import { supabase } from "@/config/supabase";
import type { AppUser } from "@/types/models";
import { logger } from "@/utils/logger";

function normalizeEmail(email: unknown) {
  return typeof email === "string" && email.trim()
    ? email.trim().toLowerCase()
    : null;
}

function normalizeDisplayName(displayName: string) {
  return displayName.trim().replace(/\s+/g, " ").slice(0, 80);
}

function readMetadataString(metadata: Record<string, unknown>, keys: string[]) {
  for (const key of keys) {
    const value = metadata[key];
    if (typeof value === "string" && value.trim()) {
      return normalizeDisplayName(value);
    }
  }
  return null;
}

export function deriveOAuthDisplayName(
  authUser: User,
  existingDisplayName?: string | null,
) {
  const metadata = (authUser.user_metadata ?? {}) as Record<string, unknown>;
  const metadataName =
    readMetadataString(metadata, [
      "display_name",
      "full_name",
      "name",
      "given_name",
    ]) ?? null;

  const email = normalizeEmail(authUser.email);
  const emailFallback = email ? email.split("@")[0] ?? "Curator" : "Curator";

  if (existingDisplayName?.trim()) {
    const normalizedExisting = normalizeDisplayName(existingDisplayName);
    const looksAutoGenerated =
      normalizedExisting.toLowerCase() === emailFallback.toLowerCase() ||
      normalizedExisting === "Curator";

    if (!looksAutoGenerated) {
      return normalizedExisting;
    }
  }

  return metadataName ?? emailFallback;
}

export function buildAppUserFromAuthUser(
  authUser: User,
  existingDisplayName?: string | null,
  existingAvatarUrl?: string | null,
): AppUser {
  const email = normalizeEmail(authUser.email) ?? "";
  const metadata = (authUser.user_metadata ?? {}) as Record<string, unknown>;
  const avatarUrl =
    existingAvatarUrl ??
    (typeof metadata.avatar_url === "string" ? metadata.avatar_url : null);

  const now = new Date().toISOString();
  return {
    id: authUser.id,
    email,
    displayName: deriveOAuthDisplayName(authUser, existingDisplayName),
    avatarUrl,
    role: "user",
    createdAt: authUser.created_at ?? now,
    updatedAt: now,
  };
}

export async function fetchExistingRemoteProfile(userId: string) {
  if (!supabase) {
    return null;
  }

  const { data, error } = await supabase
    .from("users")
    .select("display_name, avatar_url, role")
    .eq("id", userId)
    .maybeSingle();

  if (error) {
    logger.warn("auth.oauth.profile_lookup_failed");
    return null;
  }

  return data;
}
