export const tokens = {
  colors: {
    primary: "#163828",
    primaryContainer: "#2d4f3e",
    primaryFixed: "#c5ebd4",
    primaryFixedDim: "#a9cfb9",
    onPrimary: "#ffffff",
    onPrimaryContainer: "#9ac0aa",
    onPrimaryFixed: "#002113",
    onPrimaryFixedVariant: "#2c4e3d",
    secondary: "#94492e",
    secondaryContainer: "#fd9e7c",
    secondaryOnContainer: "#77331a",
    secondaryFixed: "#ffdbcf",
    secondaryFixedDim: "#ffb59c",
    onSecondary: "#ffffff",
    onSecondaryContainer: "#77331a",
    onSecondaryFixed: "#390c00",
    onSecondaryFixedVariant: "#763219",
    tertiary: "#2a3521",
    tertiaryContainer: "#404c36",
    tertiaryFixed: "#dae7c9",
    tertiaryFixedDim: "#becbae",
    onTertiary: "#ffffff",
    onTertiaryContainer: "#afbca0",
    onTertiaryFixed: "#141e0c",
    onTertiaryFixedVariant: "#3f4a35",
    background: "#fbf9f4",
    onBackground: "#1b1c19",
    surface: "#fbf9f4",
    surfaceDim: "#dbdad5",
    surfaceBright: "#fbf9f4",
    surfaceVariant: "#e4e2dd",
    surfaceContainer: "#f0eee9",
    surfaceContainerLow: "#f5f3ee",
    surfaceContainerLowest: "#ffffff",
    surfaceContainerHigh: "#eae8e3",
    surfaceContainerHighest: "#e4e2dd",
    surfaceTint: "#436653",
    onSurface: "#1b1c19",
    onSurfaceVariant: "#414844",
    inverseSurface: "#30312e",
    inverseOnSurface: "#f2f1ec",
    inversePrimary: "#a9cfb9",
    outline: "#727973",
    outlineVariant: "#c1c8c2",
    error: "#ba1a1a",
    errorContainer: "#ffdad6",
    onError: "#ffffff",
    onErrorContainer: "#93000a",
    backdrop: "rgba(27, 28, 25, 0.32)",
    transparent: "transparent",
  },
  spacing: {
    xs: 6,
    sm: 10,
    md: 16,
    lg: 24,
    xl: 32,
    xxl: 40,
    section: 48,
  },
  radius: {
    sm: 14,
    md: 20,
    lg: 28,
    pill: 999,
  },
  typography: {
    display: {
      fontFamily: "NotoSerif_700Bold",
      fontSize: 56,
      lineHeight: 62,
    },
    headline: {
      fontFamily: "NotoSerif_700Bold",
      fontSize: 34,
      lineHeight: 40,
    },
    title: {
      fontFamily: "NotoSerif_700Bold",
      fontSize: 26,
      lineHeight: 32,
    },
    body: {
      fontFamily: "Manrope_500Medium",
      fontSize: 16,
      lineHeight: 24,
    },
    label: {
      fontFamily: "Manrope_700Bold",
      fontSize: 12,
      lineHeight: 16,
      letterSpacing: 2,
    },
  },
  shadow: {
    shadowColor: "rgba(27, 28, 25, 0.04)",
    shadowOffset: { width: 0, height: 12 },
    shadowOpacity: 1,
    shadowRadius: 32,
    elevation: 0,
  },
} as const;

export type BotanicalTokens = typeof tokens;
