import type { EmptyStateContent, EmptyStateContextKey } from "./types";

export const emptyStateCopyRegistry: Record<
  EmptyStateContextKey,
  EmptyStateContent
> = {
  "dashboard.hero": {
    title: "Garden is starting",
    body: "Add your first plant to start a calm record of care, growth, and seasonal change.",
    primaryActionLabel: "Add first plant",
    tone: "firstRun",
    analyticsKey: "dashboard_hero_first_run",
  },
  "dashboard.hydration": {
    title: "Hydration",
    body: "Add your first plant to see watering rhythm and care windows here.",
    tone: "firstRun",
    analyticsKey: "dashboard_hydration_first_run",
  },
  "dashboard.gallery": {
    title: "Begin your gallery",
    body: "Add your first plant to unlock featured photography and a living timeline.",
    primaryActionLabel: "Add first plant",
    tone: "firstRun",
    analyticsKey: "dashboard_gallery_first_run",
  },
  "library.noPlants": {
    title: "Your conservatory is waiting",
    body: "Add your first plant to begin building a living collection.",
    primaryActionLabel: "Add plant",
    tone: "firstRun",
    analyticsKey: "library_no_plants",
  },
  "library.search": {
    title: "No matching plants",
    body: "Try another name, species, or location.",
    primaryActionLabel: "Clear search",
    tone: "filtered",
    analyticsKey: "library_search_empty",
  },
  "library.filter": {
    title: "No plants in this view",
    body: "Your collection has no plants matching this filter right now.",
    primaryActionLabel: "Clear filters",
    tone: "filtered",
    analyticsKey: "library_filter_empty",
  },
  "journal.noPlants": {
    title: "Begin your care journal",
    body: "Add your first plant to start logging watering, misting, feeding, and observations.",
    primaryActionLabel: "Add plant",
    tone: "firstRun",
    analyticsKey: "journal_no_plants",
  },
  "journal.noLogs": {
    title: "No care entries yet",
    body: "Log watering, misting, feeding, or observations to begin your care journal.",
    primaryActionLabel: "Add care log",
    tone: "neutral",
    analyticsKey: "journal_no_logs",
  },
  "journal.period": {
    title: "No entries for this period",
    body: "Care entries from other dates may still be available.",
    tone: "filtered",
    analyticsKey: "journal_period_empty",
  },
  "reminders.noPlants": {
    title: "Add a plant first",
    body: "Reminders attach to specimens in your collection. Add a plant to create your first schedule.",
    primaryActionLabel: "Add plant",
    tone: "firstRun",
    analyticsKey: "reminders_no_plants",
  },
  "reminders.none": {
    title: "No reminders set",
    body: "Add a reminder to keep care gentle and consistent.",
    primaryActionLabel: "Create reminder",
    tone: "neutral",
    analyticsKey: "reminders_none",
  },
  "reminders.notificationsDisabled": {
    title: "Notifications are off",
    body: "Turn on notifications in settings to receive gentle care reminders on this device.",
    primaryActionLabel: "Enable notifications",
    tone: "permission",
    analyticsKey: "reminders_notifications_disabled",
  },
  "timeline.noPhotos": {
    title: "No progress photos yet",
    body: "Add a photo when you notice new growth, a change in shape, or a moment worth remembering.",
    primaryActionLabel: "Add progress photo",
    tone: "neutral",
    analyticsKey: "timeline_no_photos",
  },
  "timeline.noPlant": {
    title: "Add a plant first",
    body: "Progress photos belong to a specimen in your collection.",
    primaryActionLabel: "Add plant",
    tone: "firstRun",
    analyticsKey: "timeline_no_plant",
  },
  "timeline.insufficientComparison": {
    title: "More moments needed",
    body: "Add at least two progress photos over time to compare growth.",
    tone: "insufficientData",
    analyticsKey: "timeline_insufficient_comparison",
  },
  "highlights.noPlants": {
    title: "Begin your highlights",
    body: "Add your first plant, then capture progress photos to build monthly highlights.",
    primaryActionLabel: "Add plant",
    tone: "firstRun",
    analyticsKey: "highlights_no_plants",
  },
  "highlights.noPhotos": {
    title: "Progress photos needed",
    body: "Monthly highlights are drawn from progress photos. Add photos as growth unfolds.",
    primaryActionLabel: "Add progress photo",
    tone: "insufficientData",
    analyticsKey: "highlights_no_photos",
  },
  "highlights.none": {
    title: "No highlights for this season",
    body: "When enough progress photos accumulate, quiet monthly highlights will appear here.",
    tone: "insufficientData",
    analyticsKey: "highlights_none",
  },
  "highlights.error": {
    title: "Unable to load highlights",
    body: "Something interrupted loading. Try again when you are ready.",
    primaryActionLabel: "Try again",
    tone: "error",
    analyticsKey: "highlights_error",
  },
  "graveyard.none": {
    title: "No memorials yet",
    body: "When a plant's time with you ends, you can preserve its story here.",
    tone: "neutral",
    analyticsKey: "graveyard_none",
  },
  "archive.premiumLocked": {
    title: "Archive curation",
    body: "Premium quietly pairs before-and-after photos from remembered specimens to reveal growth over time.",
    primaryActionLabel: "View Premium",
    tone: "premium",
    analyticsKey: "archive_premium_locked",
  },
  "archive.insufficientData": {
    title: "More photos needed",
    body: "Add progress photos to active plants before archiving. Pairs emerge from remembered growth moments.",
    tone: "insufficientData",
    analyticsKey: "archive_insufficient_data",
  },
  "archive.noPairs": {
    title: "No pairings yet",
    body: "When before-and-after photos exist for a remembered specimen, quiet pairs will appear here.",
    tone: "neutral",
    analyticsKey: "archive_no_pairs",
  },
  "archive.noMemorials": {
    title: "No memorials yet",
    body: "Archive gallery draws from plants remembered in the Graveyard.",
    tone: "neutral",
    analyticsKey: "archive_no_memorials",
  },
  "profile.streakZero": {
    title: "0",
    body: "Your care rhythm begins with the first log.",
    tone: "firstRun",
    analyticsKey: "profile_streak_zero",
  },
  "plantActivity.noLogs": {
    title: "No care entries yet",
    body: "Log watering, misting, feeding, or observations to begin this specimen's chronicle.",
    tone: "neutral",
    analyticsKey: "plant_activity_no_logs",
  },
  "plantDetail.noCareLogs": {
    title: "No care entries yet",
    body: "Your care rhythm begins with the first log.",
    primaryActionLabel: "Log care",
    tone: "neutral",
    analyticsKey: "plant_detail_no_care_logs",
  },
  "plantDetail.noPhotos": {
    title: "No progress photos yet",
    body: "Add a photo when you notice new growth, a change in shape, or a moment worth remembering.",
    primaryActionLabel: "Add progress photo",
    tone: "neutral",
    analyticsKey: "plant_detail_no_photos",
  },
  "specimenTags.noPlants": {
    title: "No specimen tags yet",
    body: "Add a plant to generate botanical QR labels for consistent identification.",
    primaryActionLabel: "Add plant",
    tone: "firstRun",
    analyticsKey: "specimen_tags_no_plants",
  },
  "ai.insufficientData": {
    title: "More history needed",
    body: "This insight needs additional care logs or photos before it can offer a thoughtful read.",
    tone: "insufficientData",
    analyticsKey: "ai_insufficient_data",
  },
  "ai.premiumRequired": {
    title: "Premium insight",
    body: "This editorial feature is included with Premium membership.",
    primaryActionLabel: "View Premium",
    tone: "premium",
    analyticsKey: "ai_premium_required",
  },
  "ai.quotaReached": {
    title: "Monthly limit reached",
    body: "You have used this month's AI allowance. It renews quietly at the start of next month.",
    tone: "neutral",
    analyticsKey: "ai_quota_reached",
  },
  "ai.fallback": {
    title: "Quiet local insight",
    body: "Cloud insight is unavailable. A calm on-device summary is shown instead.",
    tone: "neutral",
    analyticsKey: "ai_fallback",
  },
  "ai.offline": {
    title: "Offline",
    body: "Reconnect to refresh cloud insights. Local care data remains on this device.",
    tone: "offline",
    analyticsKey: "ai_offline",
  },
  "ai.error": {
    title: "Unable to load insight",
    body: "Something interrupted this request. Try again when you are ready.",
    primaryActionLabel: "Try again",
    tone: "error",
    analyticsKey: "ai_error",
  },
  "backup.noHistory": {
    title: "No sync history yet",
    body: "After your first backup or sync, a quiet record of activity will appear here.",
    tone: "neutral",
    analyticsKey: "backup_no_history",
  },
  "backup.unavailable": {
    title: "Backup unavailable",
    body: "Sign in and configure cloud backup to protect your collection on this device.",
    tone: "neutral",
    analyticsKey: "backup_unavailable",
  },
  "backup.localOnly": {
    title: "Local collection",
    body: "Your plants and care history live on this device until cloud backup is enabled.",
    tone: "neutral",
    analyticsKey: "backup_local_only",
  },
  "backup.noRecords": {
    title: "No backup records",
    body: "Run a backup when you are ready to create the first archive entry.",
    primaryActionLabel: "Back up now",
    tone: "neutral",
    analyticsKey: "backup_no_records",
  },
  "backup.failed": {
    title: "Backup did not complete",
    body: "The last attempt stopped before finishing. Try again when your connection is steady.",
    primaryActionLabel: "Try again",
    tone: "error",
    analyticsKey: "backup_failed",
  },
  "sync.abandoned": {
    title: "Sync items need attention",
    body: "Some changes could not reach the cloud. Review and retry when you are ready.",
    primaryActionLabel: "Review sync",
    tone: "error",
    analyticsKey: "sync_abandoned",
  },
  "sync.repairQueueEmpty": {
    title: "Backup queue is clear",
    body: "No failed or interrupted sync items need attention right now.",
    tone: "neutral",
    analyticsKey: "sync_repair_queue_empty",
  },
  "premium.offeringsUnavailable": {
    title: "Plans unavailable",
    body: "Subscription options could not be loaded. Check your connection and try again.",
    primaryActionLabel: "Try again",
    tone: "error",
    analyticsKey: "premium_offerings_unavailable",
  },
  "premium.entitlementUnavailable": {
    title: "Subscription status unavailable",
    body: "We could not verify membership right now. Your collection remains on this device.",
    tone: "neutral",
    analyticsKey: "premium_entitlement_unavailable",
  },
  "premium.alreadySubscribed": {
    title: "Membership active",
    body: "Your Premium membership is already active on this account.",
    tone: "neutral",
    analyticsKey: "premium_already_subscribed",
  },
  "premium.restoreUnavailable": {
    title: "Restore unavailable",
    body: "We could not reach the store to restore purchases. Try again when your connection is steady.",
    primaryActionLabel: "Try again",
    tone: "error",
    analyticsKey: "premium_restore_unavailable",
  },
  "featureRequests.searchEmpty": {
    title: "No matching ideas",
    body: "Try another phrase or browse popular requests below.",
    tone: "filtered",
    analyticsKey: "feature_requests_search_empty",
  },
  "featureRequests.mineEmpty": {
    title: "No ideas shared yet",
    body: "When you share a feature idea, it will appear here for you to follow.",
    primaryActionLabel: "Share an idea",
    tone: "neutral",
    analyticsKey: "feature_requests_mine_empty",
  },
};
